[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/content.json"
  to = "/.netlify/functions/content-api?uid=:uid&blogId=:blogId"
  status = 200

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/products.json"
  to = "/.netlify/functions/product-api?uid=:uid&blogId=:blogId"
  status = 200

[[redirects]]
  from = "/api/admin/content"
  to = "/.netlify/functions/admin-content"
  status = 200

[[redirects]]
  from = "/api/admin/products"
  to = "/.netlify/functions/admin-product"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200