[build]
functions = "netlify/functions"
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api/admin/storage"
to = "/.netlify/functions/admin-storage"
status = 200

[[redirects]]
from = "/api/admin/blog"
to = "/.netlify/functions/admin-blog"
status = 200

[[redirects]]
from = "/api/admin/users"
to = "/.netlify/functions/admin-users"
status = 200

[[redirects]]
from = "/api/admin/content"
to = "/.netlify/functions/admin-content"
status = 200

[[redirects]]
from = "/api/admin/product"
to = "/.netlify/functions/admin-product"
status = 200

[[redirects]]
from = "/api/content"
to = "/.netlify/functions/content-api"
status = 200

[[redirects]]
from = "/api/product"
to = "/.netlify/functions/product-api"
status = 200

[[redirects]]
from = "/api/export/content"
to = "/.netlify/functions/export-content"
status = 200

[[redirects]]
from = "/api/import/content"
to = "/.netlify/functions/import-content"
status = 200

[[redirects]]
from = "/api/export/products"
to = "/.netlify/functions/export-products"
status = 200

[[redirects]]
from = "/api/import/products"
to = "/.netlify/functions/import-products"
status = 200

[[redirects]]
from = "/users/:uid/blogs/:blogId/api/content.json"
to = "/.netlify/functions/content-api"
status = 200

[[redirects]]
from = "/users/:uid/blogs/:blogId/api/products.json"
to = "/.netlify/functions/product-api"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200