[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/content.json"
  to = "/.netlify/functions/content-api"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin-content/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200